import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./components/Sidebar";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <main
          className={twMerge(
            // Estilização base
            "min-h-screen",
            // Responsive only
            "lg:grid lg:grid-cols-app",
            // Darkmode only
            "dark:bg-zinc-900"
          )}
        >
          <Sidebar />
          <section
            className={twMerge(
              // Estilização base
              "max-w-[100vw] px-4 pb-12 pt-24 lg:px-8 lg:pb-12",
              // Responsive only
              "lg:pt-8 lg:col-start-2"
            )}
          >
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
